#pragma once
#include "resources/archive.hpp"
#include <array>
#include <map>
#include <optional>

namespace d2x {
inline constexpr std::array<int, 5> actTownLevels{1, 40, 75, 103, 109};
enum class GenerationKind { None, Maze, Preset, Outdoor };
struct LevelPopulation {
    bool supported = false, rangedFirst = false;
    int types = 0, warpDistanceSquared = 0;
    std::array<int, 3> density{}, uniqueMin{}, uniqueMax{}, level{};
    std::vector<std::string> normal, nightmareHell, unique;
    std::array<std::string, 4> critters;
    std::array<int, 4> critterChance{}, critterAmount{};
};
struct LevelRecord {
    int id = 0, act = 0, levelType = 0;
    int palette = 0;
    bool isInside = false, losDraw = false;
    bool town = false;
    int lightIntensity = 0, lightRed = 0, lightGreen = 0, lightBlue = 0;
    GenerationKind generation = GenerationKind::None;
    std::string name;
    int width = 0, height = 0, subtype = -1, theme = -1, waypoint = -1;
    int shrineSubstitution = -1, waypointSubstitution = -1;
    std::optional<int> objectLevel; // Levels.MonLvl1, not the expansion/difficulty level.
    int offsetX = 0, offsetY = 0, depend = 0;
    std::array<int, 8> visible{}, warps{}, objectGroups{}, objectProbabilities{};
    LevelPopulation population;
};
struct PresetRecord {
    int id = 0, level = 0, width = 0, height = 0, files = 0;
    std::string name;
    uint32_t dt1Mask = 0;
    bool fillBlanks = false, killEdge = false, populate = false;
    bool scan = false, outdoors = false;
    bool automap = false;
    bool animate = false;
    int animationSpeed = 0;
    int pops = 0, popPad = 0;
    std::array<std::string, 6> variants;
};
struct MazeRecord {
    int level = 0, rooms = 0, width = 0, height = 0, merge = 0;
    std::array<int, 3> difficultyRooms{};
};
struct SubstitutionRecord {
    int type = 0, gridSize = 0, borderType = 0;
    std::string name, file;
    uint32_t dt1Mask = 0;
    bool checkAll = false;
    std::array<int, 5> probability{}, trials{}, maximum{};
};
struct WarpRecord {
    int id = 0, selectX = 0, selectY = 0, selectWidth = 0, selectHeight = 0;
    int exitX = 0, exitY = 0, offsetX = 0, offsetY = 0;
    bool litVersion = false;
    int tiles = 0;
    std::string name, direction;
};
struct MapPiece {
    int x = 0, y = 0, width = 0, height = 0, preset = 0, variant = 0;
    std::string ds1;
    std::vector<std::string> tileLibraries;
    bool fillBlanks = false;
    bool populate = true;
    int substitutionGroup = -1;
    bool killEdge = false;
    int animationSpeed = -1; // Disabled; native zero speed means 80/256 frames per tick.
    int substitutionVariant = 0;
    int pops = -1, popPad = 0;
};
struct MapRecipe {
    struct NativeRequest { int level{}; uint32_t seed{}; int difficulty{}; };
    std::optional<NativeRequest> native;
    int preset = 0, variant = 0, levelType = 0;
    int act = -1;
    std::string ds1;
    std::vector<std::string> tileLibraries;
    bool fillBlanks = false;
    bool killEdge = false;
    int animationSpeed = -1;
    int pops = -1, popPad = 0;
    std::vector<MapPiece> pieces;
    // Outdoor terrain is generated by DRLG; DS1s supply authored overlays.
    int width = 0, height = 0, worldX = 0, worldY = 0;
    uint32_t baseFloor = 0;
    struct FloorOverride {
        int x = 0, y = 0;
        uint32_t value = 0;
    };
    std::vector<FloorOverride> floorOverrides;
    struct BlankArea {
        int x = 0, y = 0, width = 0, height = 0;
    };
    std::vector<BlankArea> blankAreas;
    struct Boundary {
        int destination = 0, side = 0, start = 0, end = 0;
        int contactStart = 0, contactEnd = 0;
        int plane = -1;
        // Authored dirt road crossing, in local tile coordinates; not a guessed gate centre.
        int pathStart = -1, pathEnd = -1;
        int coordinate(int width, int height) const {
            return plane >= 0 ? plane : side == 3 ? width : side == 0 ? height : 0;
        }
    };
    std::vector<Boundary> boundaries;
};
// A catalog entry is not proof that the runtime can generate the corresponding level.
struct LevelAvailability {
    std::optional<MapRecipe> recipe;
    std::vector<std::string> missing;
    std::string reason;
    bool ready() const { return recipe.has_value() && missing.empty() && reason.empty(); }
};
class WorldCatalog {
    std::map<int, LevelRecord> levels_;
    std::map<int, PresetRecord> presets_;
    std::map<int, std::array<std::string, 32>> types_;
    std::map<int, MazeRecord> mazes_;
    std::vector<SubstitutionRecord> substitutions_;
    std::map<int, std::vector<WarpRecord>> warps_;
    std::vector<std::string> diagnostics_;

  public:
    explicit WorldCatalog(Archives &archives, int difficulty = 0);
    const auto &levels() const { return levels_; }
    const auto &presets() const { return presets_; }
    const auto &mazes() const { return mazes_; }
    const auto &substitutions() const { return substitutions_; }
    const auto &warps() const { return warps_; }
    const auto &diagnostics() const { return diagnostics_; }
    const LevelRecord &level(int id) const;
    MapRecipe preset(int id, int levelType, int variant = 0) const;
    std::vector<std::string> missing(Archives &archives, const MapRecipe &recipe) const;
    LevelAvailability availability(Archives &archives, int levelId, int variant = 0) const;
    std::vector<std::string> typeLibraries(int levelType) const;
    std::vector<std::string> terrainLibraries(int levelType, uint32_t mask) const;
};
} // namespace d2x
