include(FetchContent)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(STORM_USE_BUNDLED_LIBRARIES ON CACHE BOOL "" FORCE)
set(STORM_SKIP_INSTALL ON CACHE BOOL "" FORCE)
foreach(dep IN ITEMS raylib stormlib)
  if(EXISTS "${CMAKE_SOURCE_DIR}/external/${dep}/CMakeLists.txt")
    add_subdirectory(external/${dep} EXCLUDE_FROM_ALL)
  elseif(dep STREQUAL "raylib")
    FetchContent_Declare(raylib GIT_REPOSITORY https://github.com/raysan5/raylib.git GIT_TAG c1ab645ca298a2801097931d1079b10ff7eb9df8)
    FetchContent_MakeAvailable(raylib)
  else()
    FetchContent_Declare(stormlib GIT_REPOSITORY https://github.com/ladislav-zezula/StormLib.git GIT_TAG 86f9b99ffe4d3417dad16d00541cf6f2e3d7bf79)
    FetchContent_MakeAvailable(stormlib)
  endif()
endforeach()
